INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (5, 'Abacavir', 'ZIHAGEN', 11.38);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (6, 'Ácido bempedoico', 'NEXLETOL', 5.48);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (7, 'Ácido etacrínico', 'EDECRIN', 8.54);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (8, 'Bacitracina', 'NEOSPORIN', 1.25);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (9, 'Bacitracin/neomycin/polymyxin B', 'BACIIM', 14.58);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (10, 'Baclofen', 'LIORESAL', 3.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (11, 'Baloxavir marboxil', 'XOFLUZA', 7.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (12, 'Carbidopa', 'LODOSYN', 1.75);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (13, 'Carbidopa/levodopa', 'SINEMET', 5.45);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (14, 'Carbinoxamine', 'KARBINAL ER', 18.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (15, 'Carboplatin', 'No US brand name', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (16, 'Carfilzomib', 'KYPROLIS', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (17, 'Dimethyl sulfoxide', 'CERVIDIL, PREPIDIL, PROSTIN E2', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (18, 'Dinoprostone', 'UNITUXIN', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (19, 'Dinutuximab', 'Benadryl', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (20, 'Difenhidramina', 'RIMSO-50', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (21, 'Diphenoxylate/atropine', 'LOMOTIL', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (22, 'Enfuvirtide', 'FUZEON', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (23, 'Enoxaparina', 'LOVENOX', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (24, 'Entacapona', 'COMTAN', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (25, 'Entecavir', 'BARACLUDE', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (26, 'Enzalutamide', 'XTANDI', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (27, 'Fluvoxamina', 'LUVOX', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (28, 'Fomepizol', 'ANTIZOL', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (29, 'Fondaparinux', 'ARIXTRA', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (30, 'Formoterol', 'FORADIL, PERFOROMIST', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (32, 'Foscarnet', 'FOSCAVIR', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (33, 'Goserelin', 'SANCUSO', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (34, 'Granisetrón', 'GRIS-PEG', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (35, 'Griseofulvina', 'NEURONTIN', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (36, 'Gabapentina', 'ZOLADEX', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (37, 'Hidroxocobalamina', 'PLAQUENIL', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (38, 'Hidroxicloroquina', 'CYANOKIT', 6.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (39, 'Ibuprofeno', 'ADVIL, MOTRIN IB', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (40, 'Ibutilida', 'CORVERT', 32.12);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (41, 'Icatibant', 'FIRAZYR', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (42, 'Litio', 'LITHOBID', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (43, 'Lixisenatida', 'ADLYXIN', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (45, 'Metanfetamina', 'MOBIC', 26.70);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (46, 'Megestrol', 'DESOXYN', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (47, 'Meloxicam', 'MEGACE', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (48, 'Nicotine', 'COMMIT, NICORETTE, NICOTROL', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (49, 'Oxitocina', 'PITOCIN', 0.00);
INSERT INTO medicamentos (id_medicamento, nom_generico, nom_comercial, precio_m) VALUES (50, 'Paracetamol (acetaminofeno)', 'TYLENOL', 14.98);
